<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    /* новости */
    'News' => 'Новости',    
    'Create News' => 'Добавить новость',    
    'Update News: ' => 'Редактирование новости: ',   
    
    /* страницы */
    'Pages' => 'Страницы',    
    'Create Page' => 'Добавить страницу',
    'Update Page: ' => 'Редактирование страницы: ',
    
    'Update' => 'Редактирование',
    'Create' => 'Добавить',
    'Save' => 'Сохранить',
    
    /* события */
    'Event' => 'Событие',
    'Events' => 'События',
    'Create Event' => 'Добавить событие',
    'Update Event' => 'Редактировать событие',
    'Event Categories' => 'Категории событий',
    //'Event Delete' => 'События',
    
    'Category' => 'Категория',
    'Categories' => 'Категории',
    'Create Category' => 'Добавить категорию',
    'Update Category: ' => 'Редактирование категории: ',
    
    'Event Attributes' => 'Атрибуты',
    'Create Attribute' => 'Добавить атрибут',
    'Update Event: ' => 'Редактирование события: ',
    'Update Attribute: ' => 'Редактирование атрибута: ',
    'Attribute List' => 'Список атрибутов',
    'Event List' => 'Список событий',
    'No' => 'Нет',
    'Yes' => 'Да',
    
);
